### ISSUE TITLE
Somthing between verion 0.9.0 and 0.9.1 has broken -I feature

### ISSUE THREAD

**Issue by aomega** [visionmedia/expresso#138]
Hi,

I noticed today that our unit tests have started failing, even though we have not changed our code in the interim. I tracked it down to a version change between 0.9.0 and 0.9.1 of expresso. We use the -I option to name the lib directory for the tests. This works in 0.9.0. In 0.9.1 we get the error:

> expresso -I lib

   uncaught undefined: Error: Cannot find module 'purger'
    at Function._resolveFilename (module.js:317:11)
    at Function._load (module.js:262:25)
    at require (module.js:346:19)
    at Object.<anonymous> (/home/jroberts/workspace/logger/test/test-purger.js:11:14)
    at Module._compile (module.js:402:26)
    at Object..js (module.js:408:10)
    at Module.load (module.js:334:31)
    at Function._load (module.js:293:12)
    at require (module.js:346:19)
    at runFile (/home/jroberts/workspace/logger/node_modules/expresso/bin/expresso:810:15)
