### ISSUE TITLE
assert.length not working with node 0.6.0

### ISSUE THREAD

**Issue by renajohn** [visionmedia/expresso#152]
When using assert.length, I have the following error:

> expresso -s test/test-server.js

```
uncaught undefined: TypeError: Property 'length' of object function ok(value, message) {
  if (!!!value) fail(value, true, message, '==', assert.ok);
} is not a function
    at Object._onTimeout (test/test-server.js:31:14)
    at Timer.ontimeout (timers.js:84:39)

Property 'length' of object function ok(value, message) {
  if (!!!value) fail(value, true, message, '==', assert.ok);
} is not a function
TypeError: Property 'length' of object function ok(value, message) {
  if (!!!value) fail(value, true, message, '==', assert.ok);
} is not a function
    at Object._onTimeout (test/test-server.js:31:14)
    at Timer.ontimeout (timers.js:84:39)...
```
